"""
confidence_scorer.py
---------------------
Estimates speaker confidence from text using zero-shot classification on any language.

Uses joeddav/xlm-roberta-large-xnli to dynamically classify the transcript
against the contrastive candidate labels ["confident", "hesitant"]. The probability
of the "confident" class is used directly as the linguistic confidence score.
"""

from __future__ import annotations

import logging
import torch
from transformers import pipeline  # type: ignore

logger = logging.getLogger(__name__)

# Force MPS if available, fallback to CPU
_DEVICE = "mps" if torch.backends.mps.is_available() else "cpu"
logger.info("Using device for Zero-Shot Confidence Analysis: %s", _DEVICE)

# ---------------------------------------------------------------------------
# Module-level eager cache
# ---------------------------------------------------------------------------
_zero_shot_pipeline = pipeline(
    task="zero-shot-classification",
    model="joeddav/xlm-roberta-large-xnli",
    device=_DEVICE,
)


def _get_pipeline():
    """Return the cached zero-shot classification pipeline."""
    return _zero_shot_pipeline


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def score_confidence(text: str) -> dict:
    """Score the linguistic confidence of *text* natively in any language.

    Uses a zero-shot classification model:
    ``joeddav/xlm-roberta-large-xnli``

    Scores are generated by predicting the candidate labels ["confident", "hesitant"].

    Parameters
    ----------
    text:
        Raw transcript text to analyse.

    Returns
    -------
    dict
        Keys (structured to maintain perfect backward compatibility with fusion scoring):

        * ``"emotion_confidence"``   – confidence score ∈ [0, 1]
        * ``"lexicon_confidence"``   – confidence score ∈ [0, 1]
        * ``"linguistic_confidence"``– confidence score ∈ [0, 1]
    """
    if not text or not text.strip():
        return {
            "emotion_confidence": 0.0,
            "lexicon_confidence": 0.0,
            "linguistic_confidence": 0.0,
        }

    try:
        pipe = _get_pipeline()
        
        # Predict the candidate labels
        result = pipe(text, candidate_labels=["confident", "hesitant"])
        
        # Format mapping: e.g. {"labels": ["confident", "hesitant"], "scores": [0.85, 0.15]}
        scores = dict(zip(result["labels"], result["scores"]))
        confidence_score = float(scores.get("confident", 0.0))
        
    except Exception as exc:
        logger.error("Zero-shot confidence scoring failed: %s", exc)
        confidence_score = 0.5  # Fallback to balanced mid-point if inference crashes

    return {
        "emotion_confidence": confidence_score,
        "lexicon_confidence": confidence_score,
        "linguistic_confidence": confidence_score,
    }
